In [45]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import recall_score,classification_report,confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from imblearn.combine import SMOTEENN
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

In [4]:
df=pd.read_csv('tel_churn.csv')

In [7]:
df= df.drop('Unnamed: 0',axis=1)

In [9]:
df.head()

SeniorCitizen  MonthlyCharges  TotalCharges  Churn  gender_Female  \
0              0           29.85         29.85      0              1   
1              0           56.95       1889.50      0              0   
2              0           53.85        108.15      1              0   
3              0           42.30       1840.75      0              0   
4              0           70.70        151.65      1              1   

   gender_Male  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  ...  \
0            0           0            1              1               0  ...   
1            1           1            0              1               0  ...   
2            1           1            0              1               0  ...   
3            1           1            0              1               0  ...   
4            0           1            0              1               0  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  Tenure_group_0-11  Tenure_group_12-23  \
0                           0                  1                   0   
1                           1                  0                   0   
2                           1                  1                   0   
3                           0                  0                   0   
4                           0                  1                   0   

   Tenure_group_24-35  Tenure_group_36-47  Tenure_group_48-59  \
0                   0                   0                   0   
1                   1                   0                   0   
2                   0                   0                   0   
3                   0                   1                   0   
4                   0                   0                   0   

   Tenure_group_60-71  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 51 columns]

In [16]:
# Creating x and y variable 
x= df.drop('Churn',axis=1)
y=df['Churn']
y=np.array(y)

In [19]:
x=np.array(x)
print(x)

[[0.0000e+00 2.9850e+01 2.9850e+01 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 5.6950e+01 1.8895e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 5.3850e+01 1.0815e+02 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 ...
 [0.0000e+00 2.9600e+01 3.4645e+02 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e+00 7.4400e+01 3.0660e+02 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0565e+02 6.8445e+03 ... 0.0000e+00 0.0000e+00 1.0000e+00]]


In [20]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=123) 

Making a Decision Tree Calssifier

In [36]:
model_dt=DecisionTreeClassifier(max_depth=6,min_samples_leaf=9)

In [37]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=9)

In [38]:
y_pred=model_dt.predict(x_test)

Accuracy Score

In [39]:
print(accuracy_score(y_test,y_pred)*100)

79.317697228145


In [41]:
# Classification Report
print(classification_report(y_test,y_pred,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86       996
           1       0.68      0.56      0.61       411

    accuracy                           0.79      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.79      0.79      0.79      1407



In [43]:
# Confusion Matrix
print(confusion_matrix(y_test,y_pred))

[[885 111]
 [180 231]]


In [57]:
# Dealing with the imbalanced dataset

sm= SMOTE()
x_resampled,y_resampled=sm.fit_resample(x,y)

In [51]:
xr_train,xr_test,yr_train,yr_test= train_test_split(x_resampled,y_resampled,test_size=0.2,random_state=123) 

In [49]:
model_smote=DecisionTreeClassifier(max_depth=6,min_samples_leaf=9)

In [50]:
model_smote.fit(xr_train,yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=9)

In [52]:
y_pred_smote=model_smote.predict(xr_test)

In [53]:
print(accuracy_score(y_pred_smote,yr_test)*100)

80.97773475314618


In [54]:
# Classification Report
print(classification_report(yr_test,y_pred_smote,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.77      0.80      1031
           1       0.79      0.85      0.82      1035

    accuracy                           0.81      2066
   macro avg       0.81      0.81      0.81      2066
weighted avg       0.81      0.81      0.81      2066



In [61]:
# RandomForest Classifier
model_rf= RandomForestClassifier(n_estimators=150)
model_rf.fit(xr_train,yr_train)

RandomForestClassifier(n_estimators=150)

In [62]:
y_pred_smote2=model_rf.predict(xr_test)

In [63]:
print(accuracy_score(y_pred_smote2,yr_test)*100)

84.26911907066795


In [64]:
print(classification_report(yr_test,y_pred_smote2,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1031
           1       0.87      0.80      0.84      1035

    accuracy                           0.84      2066
   macro avg       0.84      0.84      0.84      2066
weighted avg       0.84      0.84      0.84      2066



In [66]:
print(confusion_matrix(yr_test,y_pred_smote2))

[[910 121]
 [204 831]]


In [67]:
# Saving the model
import pickle
file_loc='model.sav'
pickle.dump(model_rf,open(file_loc,'wb'))

In [68]:
load_model=pickle.load(open(file_loc,'rb'))

In [69]:
print(load_model.score(xr_test,yr_test))

0.8426911907066795
